#Dissecando uma variavel
a = input("Digite algo: ")
print(f"O tipo primitivo e ? {type(a)} ")
print(f"So tem espacos ? {a.isspace()} ")
print(f"E um numero ? {a.isnumeric()} ")
print(f"E alfabetico ? {a.isalpha()} ")
print(f"E alfanumerico ? {a.isalnum()} ")
print(f"Esta em maiuscula ? {a.isupper()} ")
print(f"Esta em minusculo ? {a.islower()} ")
print(f"E capitalizada ? {a.istitle()} ")